spring.application.name=springbasicfinal

# 以下の行を追記
# MySQL の接続設定
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/springbasicfinal}
# MySQL にログインする時のユーザ名
spring.datasource.username=${DB_USERNAME:root}
# MySQL にログインする時のパスワード
spring.datasource.password=${DB_PASSWORD:}
# データベース接続に使用するJDBCドライバーのクラス名
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# 実行されるSQLがコンソールに出力される
spring.jpa.show-sql=true
# Spring Boot起動時にテーブルの自動生成を行う
spring.jpa.hibernate.ddl-auto=update